### ISSUE TITLE
WARNING: The graph has an edge between non-existant node(s)

### ISSUE THREAD

**Issue by lane-zhao** [SchulzLab/Aeron#1]
I used GraphBuilder.py to genenrated hg38.gfa . Then when I ran the step ”align_with_secondaries“ in the snakemakefusion，it always have an error as:  WARNING: The graph has an edge between non-existant node(s) .  Is there something wrong in GraphBuilder ?

**Comment by ddurai** [comment]
Dear Lane Zao,
Thank you for trying our software and pointing out the issue. In cases where two nodes arise from the same genomic region (with the same genomic coordinates), we keep only one node and remove the other. But I realized the graph builder is still building an edge between the two nodes. But this would not affect the alignment, quantification and gene-fusion detection process

**Comment by lane-zhao** [comment]
Thanks for your reply. But when I run the step “align_with_secondaries”use the commond: /usr/bin/time -v Binaries/Aligner --all-alignments -g input/hg.gfa -f input/1.fq --try-all-seeds --seeds-mxm-length 17 --seeds-mem-count 20 --seeds-mxm-cache-prefix tmp/seeds_hg38_index -a secondary.gam -t 40 -b 35 --E-cutoff 1
 It print the same warning from beginning to end like: The graph has an edge between non-existant node(s). It generated a big log file.  It sames like all genes and nodes have the same  problems. Besides the WARNINGS, The log file is as follows and the size of secondary.gam I  get form this command is only 4kb.  


Build seeder from the graph
0 original nodes
0 split nodes
0 ambiguous split nodes
0 edges
0 nodes with in-degree >= 2
MUM seeds, min length 20, max count 18446744073709551615
Initial bandwidth 5, ramp bandwidth 10, tangle effort 10000
Align
Alignment finished
Input reads: 6097178 (6028409960bp)
Seeds found: 0
Seeds extended: 0
Reads with a seed: 0 (0bp)
Reads with an alignment: 0
Output alignments: 0 (0bp)
Output end-to-end alignments: 0 (0bp)
        Command being timed: "Binaries/Aligner -g input/hg38.gfa -f input/1.fq -a secondary.gam -t 39"
        User time (seconds): 937.48
        System time (seconds): 107.18
        Percent of CPU this job got: 229%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 7:35.13
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1130496
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 367540
        Voluntary context switches: 1164583
        Involuntary context switches: 44878
        Swaps: 0
        File system inputs: 10111856
        File system outputs: 2646752
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0


| |
zhaolei_lane
|
|
zhaolei_lane@163.com
|
签名由网易邮箱大师定制
On 2/24/2020 19:15，ddurai<notifications@github.com> wrote：

Dear Lane Zao,
Thank you for trying our software and pointing out the issue. In cases where two nodes arise from the same genomic region (with the same genomic coordinates), we keep only one node and remove the other. But I realized the graph builder is still building an edge between the two nodes. But this would not affect the alignment, quantification and gene-fusion detection process

**Comment by ddurai** [comment]
Dear Lane Zao,
Can you please point me to the input fastq file you are using and also can you attach the log file here

**Comment by lane-zhao** [comment]
The fastq file I used is from Nanopore  cDNA longreads sequenece about  human tissue.
The .gfa file is used GraphBuilder.py to generated.
I supposed their have something wrong in GraphBuilder.py . 

[Aligner.log](https://github.com/SchulzLab/Aeron/files/4250408/Aligner.log)

**Comment by SchulzLab** [comment]
Dear lane-zhao,
can you please give more information on the annotation file you use and the command for building the graph file.

Thanks,
Marcel

**Comment by lane-zhao** [comment]
The genome and gtf file was download from ensemble  version: release-94 Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa  and corresponding gtf file.
The command I used is >python GraphBuilder.py -e  Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -g hg38.gtf -o hg38.gfa
The format of the gtf file and hg38.gfa which I generated are in the attach.txt 

[attach.txt](https://github.com/SchulzLab/Aeron/files/4253779/attach.txt)

**Comment by ddurai** [comment]
Dear Lane Zao
The format of the genome file you used was slightly different than the format which we used for generating the graph and testing our codes. This difference was not accounted for in the previous version of the GraphBuilder script. I have fixed the bug and uploaded the new version. Can you please try generating the graph file again with the new version and test the aligner. I apologize for the inconvenience caused to you in this regards

**Comment by ddurai** [comment]
Dear Lane Zao
The format of the genome file you used was slightly different than the format which we used for generating the graph and testing our codes. This difference was not accounted for in the previous version of the GraphBuilder script. But I assure you that this bug does not change the results which we have reported in the manuscript.
I have fixed the bug and uploaded the new version. Can you please try generating the graph file again with the new version and test the aligner. I apologize for the inconvenience caused to you

**Comment by lane-zhao** [comment]
The updated script is working well. But then I have a new question, in   file Snakefile_fusion， line 61:	transcriptaln = "output/aln_{transcripts}_{graph}_full_length.gam",   any steps to generated this file ?
The error is : MissingInputException in line 59 of Snakefile_fusion: `input files for rule pair_assignments.    I supposed this step was  missed.
