### ISSUE TITLE
ERROR in rule align

### ISSUE THREAD

**Issue by Br1anChou** [SchulzLab/Aeron#11]
Hi,
  Tanks for your useful software, but I had problems in quantification part. I tried my own data(include graph file in .gfa format) and test data from https://bitbucket.org/dilipdurai/aeron/src/master/snakemake_pipeline/input/input.tar, both got the same error messages:

```
Error in rule align:
        jobid: 12
        output: output/aln_ReferenceTranscriptFastaFile_HumanUpdated38V5_all.gam
        log: tmp/aligner_stdout_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt, tmp/aligner_stderr_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt

RuleException:
CalledProcessError in line 54 of /software/Aeron/Snakefile:
Command ' set -euo pipefail;  /usr/bin/time -v Binaries/GraphAligner -g input/HumanUpdated38V5.gfa -f input/ReferenceTranscriptFastaFile.fa --try-all-seeds --seeds-mxm-length 17 --seeds-mem-count 20 --seeds-mxm-cache-prefix tmp/seedcache -a output/aln_ReferenceTranscriptFastaFile_HumanUpdated38V5_all.gam -t 10 -b 35 --greedy-length --E-cutoff 1 1> tmp/aligner_stdout_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt 2> tmp/aligner_stderr_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt ' returned non-zero exit status 1.
  File "/software/Aeron/Snakefile", line 54, in __rule_align
  File "/software/python3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /software/Aeron/.snakemake/log/2020-03-25T112637.955041.snakemake.log
```
  My command is "snakemake --cores 10 all" and my experiments were run using snakemake_5.0.0, vg_1.5.0(pre-built release version), python_3.6, and latest Aeron_f02a963.

**Comment by SchulzLab** [comment]
Hi Br1anChou,
how did you create the .gfa file? Which gtf did you use for it?

Bests,
Marcel

**Comment by maickrau** [comment]
Hi Br1anChou,

Could you please post the log files "tmp/aligner_stdout_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt" and "tmp/aligner_stderr_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt"?

**Comment by Br1anChou** [comment]
Hi Marcel,
  I used AeronScripts/GraphBuilder.py to create the .gfa file, and downloaded the .gtf file and genome sequence file from ensembl.org. when I run Graph building step, everything looks good. Please NOTE, the line 69 of ParseGTF.py, incorrect used of tabs and spaces, this will couse some errors, but I have corrected it.
 Thanks again, I would appreciate it if you can provide some necessary test files and corresponding results, to help me determine which step go wrong.

Best,
Brian

**Comment by Br1anChou** [comment]
Hi maickrau, 
I checked tmp/aligner_stderr_ReferenceTranscriptFastaFile_HumanUpdated38V5.txt, the version of libstdc++.so.6 is too low, I fixed it. Thanks for your suggestions, the software has not reported errors now.

**Comment by SchulzLab** [comment]
Hi Brian,
I am happy that it works now. Thanks for spotting the error in the ParseGTF.py file. We have fixed it.
Cheers,
Marcel
