### ISSUE TITLE
Binaries/Postprocess: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by Binaries/Postprocess)

### ISSUE THREAD

**Issue by Peiyao-Nie** [SchulzLab/Aeron#14]
Hi,
    Thanks for this useful software for Fusion-detection.It helps me a lot,However, the system version of my server is too low so that I cannot upgrade the version of glibc in the system from 2.12 to 2.17.Once I updated, my system crashed.Does this software must rely on glibc 2.17?
Actually, I hope it can be supported by glibc 2.14 or lower version.Could you help me?
Look forward to your reply.
Thank you very much.

**Comment by SchulzLab** [comment]
Dear Peiyao-Nie,
sorry but you need to use a newer version of glibc than what you currently have. 

Kind regards,
Marcel
