### ISSUE TITLE
MissingInputException in line 59 of Snakefile_fusion: `input files for rule pair_assignments

### ISSUE THREAD

**Issue by lane-zhao** [SchulzLab/Aeron#3]
In file Snakefile_fusion，line 61:    transcriptaln = "output/aln_{transcripts}_{graph}_full_length.gam", any steps to generated this file ?

The error is : MissingInputException in line 59 of Snakefile_fusion: `input files for rule pair_assignments. I supposed this step was missed.

**Comment by lane-zhao** [comment]
Hi Marcel,
I  find no steps can genetare the file "aln_{transcripts}_{graph}_full_length.gam", but both Snakefile in line 92 and  Snakefile_fusion in line 61 put this file as input, there must be **some error in the steps which can generate "aln_{transcripts}_{graph}_full_length.gam".**

**Comment by SchulzLab** [comment]
Dear Lane-zhao,
this is odd. we will look into the problem and get back to you.
Kind regards,
Marcel

**Comment by lane-zhao** [comment]
Dear Marcle,
Thanks for your great effort for this softwre.
Is there has any update about this issues?  I think this software will be very useful for progress TGS data after work out this problem.  Thanks for your  great efforts again.
Best regards,
Lane

**Comment by lane-zhao** [comment]
Drear Marcle,
Sorry for my own mistakes, there has no error in the software. Now I can run it correctly.
Lane

**Comment by liuni81** [comment]
Dear Lane-zhao,
I have the same problem with the file "output/aln_{transcripts}_{graph}_full_length.gam": looking at the Snakefile_fusion file, it seems there is no rule that can produce this output.
How did you solve it?

Many thanks.

**Comment by lane-zhao** [comment]
Hi liuni,
You can run the first two steps of  " snakemake --cores=no_of_cores all  "  to generate this file.


Lane


| |
zhaolei_lane
|
|
zhaolei_lane@163.com
|
签名由网易邮箱大师定制
On 3/12/2020 20:15，liuni81<notifications@github.com> wrote：

Dear Lane-zhao,
I have the same problem with the file "output/aln_{transcripts}_{graph}_full_length.gam": looking at the Snakefile_fusion file, it seems there is no rule that can produce this output.
How did you solve it?

Many thanks.
