### ISSUE TITLE
Missing input files for rule pair_assignments: "output/aln_{transcripts}_{graph}_full_length.gam"

### ISSUE THREAD

**Issue by liuni81** [SchulzLab/Aeron#6]
Dear,

When I run Snakefile_fusion, the snakemake environment gives me the following error: 
"MissingInputException in line 59 of Snakefile_fusion: `input files for rule pair_assignments". 

Indeed, at row 61, the script asks the file "output/aln_{transcripts}_{graph}_full_length.gam" as input, but, looking at the Snakefile_fusion file, it seems there is no rule that can produce this output. 

I'm confused.
Is there something wrong? 
Should I add a new rule in the Snakefile_fusion script?

Best Regards.

**Comment by ddurai** [comment]
Hi, 
I apologize for the late reply.  You first need to run the quantification step via "snakemake --cores=#number of cores all" and then run the snakemake fusion file. We will make it more clear in the readme file.

I apologize for the inconvenience.

regards
Dilip A Durai
