### ISSUE TITLE
AttributeError: 'ParseGTF' object has no attribute 'getTranscriptPosition'

### ISSUE THREAD

**Issue by liuni81** [SchulzLab/Aeron#8]
Dear,

When I run the command "snakemake --core=10 all", the snakemake environment gives me the following error:
in File "AeronScripts//ThreePrime.py", line 79, in <module>
    transtart, transend = gf.getTranscriptPosition(i)
AttributeError: 'ParseGTF' object has no attribute 'getTranscriptPosition'

Indeed, GraphBuilder/ParseGTF.py script file does not define the 'getTranscriptPosition' attribute.

Do you have any suggestions?

Thank you.

**Comment by ddurai** [comment]
Hi, 
Thank you for using our tool. Due to some modifications in the tool that part got modified as well. We corrected the error and uploaded the edited version of the ParseGTF file. Can you please do a git pull and try out the new version
I apologize for the inconvenience

regards
Dilip A Durai
